### ISSUE TITLE
简历模板可以搞一些蒸汽波风格的吗？

### ISSUE THREAD

**Issue by zhajingwen** [Hacker233/resume-design#204]
或者年轻有活力的配色也行，其实官网首页的配色也挺好，应用到简历模板中去也不错的
目前有的简历模板都太死灰，老气
![image](https://user-images.githubusercontent.com/33952447/197323284-8539e820-65d4-4aa6-bdae-8cc267a4513a.png)

**Comment by Hacker233** [comment]
目前正在开发积木创作模块，想要什么风格可以自己设计
