### ISSUE TITLE
进入简历制作页面后，选择了其他模块的设置后，怎么再次选择全局主题设置

### ISSUE THREAD

**Issue by dselegent** [Hacker233/resume-design#216]

**Comment by Hacker233** [comment]
可以通过点击下图中的空白区域再次进入全局主题设置。

![image](https://user-images.githubusercontent.com/28037169/230610906-82d0f4fa-774e-4871-a50c-a7089daf0cf6.png)

**Comment by dselegent** [comment]
> 可以通过点击下图中的空白区域再次进入全局主题设置。
> 
> ![image](https://user-images.githubusercontent.com/28037169/230610906-82d0f4fa-774e-4871-a50c-a7089daf0cf6.png)
