### ISSUE TITLE
简历制作的页面(views/designer)中，左右布局时，通过复制产生的模块(也就是当相同模块数大于1时)无法删除

### ISSUE THREAD

**Issue by Ocean-H1** [Hacker233/resume-design#217]
![截图](https://user-images.githubusercontent.com/74898523/230347523-4f9bfc95-ba68-42d5-abcb-9288c02a9440.png)
 **我调试之后发现，实际上第一次点击之后，该模块已经从resumeJsonNewStore.COMPONENTS中删除了，但是该页面的leftList或rightList中并没有进行响应式的同步，所以页面上该模块还是显示，造成未删除的假象**

**我在左右两列布局的情况下，放弃了使用hooks/useDeleteModel这个钩子，暂时解决了这个问题:：**
![image](https://user-images.githubusercontent.com/74898523/230348914-510dd67a-8b9c-4eaf-8118-cac52843d489.png)
![image](https://user-images.githubusercontent.com/74898523/230349120-ae2e6208-dead-401e-8300-5b62415e1b48.png)

**不过这样会多出不少重复的代码，不知道有没有更好的解决办法？**

**Comment by Hacker233** [comment]
你好，经排查确实存在此问题。之前预留了左右布局时删除模块的方法，后来好像忘记修改了。目前修改暂时采用的方法就是你上图中的写法，如果想到更优雅的代码方式，欢迎提PR。
