### ISSUE TITLE
在压缩图片时，如果原图的背景是透明的，那么压缩后图片背景将会变成黑色

### ISSUE THREAD

**Issue by Ocean-H1** [Hacker233/resume-design#221]
**这是我使用的测试图片:**
![vue3](https://user-images.githubusercontent.com/74898523/231229446-758f2c01-83d1-4df8-8610-01af9ebde2fd.png)

**这是压缩后的结果:** 
![vue3](https://user-images.githubusercontent.com/74898523/231229222-71faf998-9f74-4f5b-8fc1-391b797a594f.png)

**Comment by Hacker233** [comment]
确实是库的原因，目前还是暂时遗留该问题吧！后续该模块的功能可能会有改动。
