### ISSUE TITLE
clone下代码后 npm i run dev 后报错 是我的本地版本问题吗?

### ISSUE THREAD

**Issue by cl-cc** [Hacker233/resume-design#4]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/57168312/180154412-dc8f096f-5c64-4fcf-a260-6296f13cd23a.png">

**Comment by Hacker233** [comment]
应该是你node版本问题

**Comment by cl-cc** [comment]
那我升级一下 我这边是 12左右
<img width="356" alt="image" src="https://user-images.githubusercontent.com/57168312/180169757-00a325d5-8f51-46e3-bd23-8366cfadb433.png">
